version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: riset_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: riset_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: riset_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - WORKERS=4
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres

  frontend:
    image: nginx:alpine
    container_name: riset_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: